fixed php8 deprecation warning for libxml_disable_entity_loader()
PHPOffice/PhpSpreadsheet pull request #1625
Opened 2020-08-25 08:05 UTC by brainfoolong

This is:

```
- [x] a bugfix
```

Checklist:

- [ ] Changes are covered by unit tests
- [x] Code style is respected
- [x] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change
- [ ] Documentation is updated as necessary

### Why this change is needed?

PHP8 has deprecated the function `libxml_disable_entity_loader`. Simple fix is to check php version. More info here: https://php.watch/versions/8.0/libxml_disable_entity_loader-deprecation

2020-10-01 04:58 UTC, oleibman commented
There are 2 test modules which call the deprecated routine, and they should also be changed as part of this PR:
tests/PhpSpreadsheetTests/Reader/Security/XmlScannerTest.php
tests/PhpSpreadsheetTests/SettingsTest.php

2020-10-01 05:51 UTC, brainfoolong commented
@oleibman Alright, it's done.

2020-10-02 09:03 UTC, PowerKiKi requested changes
Code style must be fixed according to Travis errors. `composer fix` should help with that.

2020-10-05 04:54 UTC, brainfoolong commented
@PowerKiKi Hi, it's fixed now.

2020-10-08 13:02 UTC, merged

2020-10-08 22:27 UTC, flavioheleno commented
Did you notice that the changelog has been changed at the wrong history point? 
The entry is under [1.0.0-beta](https://github.com/PHPOffice/PhpSpreadsheet/pull/1625/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR563) instead of under the latest (unreleased) version..