Big fix #589. Workaround for line chart fill color
PHPOffice/PhpSpreadsheet pull request #1930
Opened 2021-03-17 12:10 UTC by tiagomalheiro

See #589

This is:

```
- [x] a bugfix
- [ ] a new feature
```

Checklist:

- [ ] Changes are covered by unit tests
- [x] Code style is respected
- [x] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change
- [ ] Documentation is updated as necessary

### Why this change is needed?

When the fill color property of `DataSeries.plotLabel` using a DataSeriesValues on a line chart is set, the XLSX file written is corrupted, and MSExcel2016 removes the drawing1.xml if forced open.
 This problem was already documented on issue #589 along with a possible solution. So all credits go to @madrussa. I am only submitting the PR.
Used the sample file [33_Chart_create_line](https://github.com/PHPOffice/PhpSpreadsheet/blob/3ab066b7d6b073f110b21ed6f6b22e9df9cfa441/samples/Chart/33_Chart_create_line.php) to test it and modified it only to include fill color:
```php
// Set the Labels for each data series we want to plot
//     Datatype
//     Cell reference for data
//     Format Code
//     Number of datapoints in series
//     Data values
//     Data Marker
//     Fill Color
$dataSeriesLabels = [
    new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_STRING, 'Worksheet!$B$1', null, 1, [], null, '98B954'), // 2010
    new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_STRING, 'Worksheet!$C$1', null, 1, [], null, 'BE4B48'), // 2011
    new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_STRING, 'Worksheet!$D$1', null, 1, [], null, '4A7EBB'), // 2012
];
```

2021-10-30 05:41 UTC, PowerKiKi requested changes

2021-10-30 05:41 UTC, PowerKiKi commented on src/PhpSpreadsheet/Writer/Xlsx/Chart.php
> +                    $objWriter->writeAttribute('val', $fillColor);
As PHPStan correctly reports, we need to handle the case where `getFillColor()` is an array. Also this should be covered by tests.

2021-11-01 03:20 UTC, PowerKiKi commented on src/PhpSpreadsheet/Writer/Xlsx/Chart.php
> +                    if ($fillColor !== null && !is_array($fillColor)) {
I'd go for the more straightforward:

```suggestion
                    if (is_string($fillColor)) {
```

2021-11-01 08:47 UTC, tiagomalheiro commented on src/PhpSpreadsheet/Writer/Xlsx/Chart.php
> +                    if ($fillColor !== null && !is_array($fillColor)) {
Totally agree. Commited, thanks

2021-11-23 14:34 UTC, merged