Fix read file xlsx
PHPOffice/PhpSpreadsheet pull request #2071
Opened 2021-05-06 23:18 UTC by hardjunior

TypeError
Argument 2 passed to PhpOffice\PhpSpreadsheet\Style\ConditionalFormatting\ConditionalFormattingRuleExtension::parseExtDataBarAttributesFromXml() must be an instance of SimpleXMLElement, null given, called in

This is:

```
- [ ] a bugfix
- [ ] a new feature
```

Checklist:

- [ ] Changes are covered by unit tests
- [ ] Code style is respected
- [ ] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change
- [ ] Documentation is updated as necessary

### Why this change is needed?

2021-06-29 20:50 UTC, MarkBaker requested changes
Is this an issue? If so, can you provide an issue number, and a test case to verify that the issue is resolved by this change

2021-06-29 20:50 UTC, MarkBaker commented on src/PhpSpreadsheet/Style/ConditionalFormatting/ConditionalFormattingRuleExtension.php
> +                    if ($dataBarXml = $extCfRuleXml->dataBar)
It's not really considered good practise to apply an assignment within an `if` test, especially when it's using a loose coercion for truthiness.

2021-10-30 05:45 UTC, PowerKiKi requested changes
Mark comment should be addressed and CI must pass before this can be merged. You can run `composer fix` to fix code style locally.

2024-05-16 04:54 UTC, oleibman commented
No update in 2.5 years. Closing.

2024-05-16 04:54 UTC, closed without merging