fix: Set font size to 10 when given 0 WIP
PHPOffice/PhpSpreadsheet pull request #2100
Opened 2021-05-15 11:48 UTC by drola

This is:

```
- [ x] a bugfix
- [ ] a new feature
```

Checklist:

- [ x] Changes are covered by unit tests
- [ x] Code style is respected
- [x ] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change
- [x] Documentation is updated as necessary

### Why this change is needed?

This change restored behavior from PHP7 in PHP8. In PHP7 calling
setSize(0) resulted in font size being set to 10. The fix addresses
change to equal comparisons in PHP8. Extra comparison is added to keep
 result from PHP7 in PHP8 for the setSize(0) case.

2021-05-20 19:15 UTC, MarkBaker commented on src/PhpSpreadsheet/Style/Font.php
> +        if ($pValue == '' || $pValue == 0) {
I think the problems with invalid values lie a little bit deeper than simply trying to set a font size to 0; try setting it to -10 and see what the resulting value is... if you're going to fix the method when given an invalid value, you should probably fix it for any invalid value, not just 0

2021-05-20 19:16 UTC, MarkBaker requested changes

2021-05-20 19:16 UTC, MarkBaker commented on tests/PhpSpreadsheetTests/Style/FontTest.php
> +    }
Tests should really include setting for negative numeric values, and for null or non-empty, non-numeric string

2021-05-20 19:18 UTC, MarkBaker commented
Thank you for the contribution; although any fix to the values passed to the method should include other invalid values as well

2021-05-26 07:49 UTC, drola commented
Thank you for the review.

I expanded the test and added the handling of all other invalid values.

2021-05-27 11:09 UTC, MarkBaker approved these changes
Thanks for making those changes to full validate the value, and for ensuring that it's covered by unit tests... 

When we first wrote those basic setters, we never really expected any developer to pass through invalid values, so the validation checks were minimal.... over the years, we've been proven wrong time and again, but never really got round to improving the validation checks, as there were always more important demands for more serious bugs or new features

2021-05-27 11:39 UTC, MarkBaker commented on src/PhpSpreadsheet/Style/Font.php
>      public function setSize($pValue)
The docblock needs modifying to `mixed` to keep phpstan happy, and it looks like phpcs is complaining about trailing white space in the comment lines.
If you can just make those changes, then the PR is good to merge

2021-05-27 11:40 UTC, MarkBaker requested changes
The docblock needs modifying to mixed to keep phpstan happy, and it looks like phpcs is complaining about trailing white space in the comment lines.
If you can just make those changes, then the PR is good to merge

2021-05-29 04:35 UTC, drola commented
Thank you. Updated the docblock, ran `composer fix`, `composer check` and rebased on top of master.

2021-05-29 09:17 UTC, merged