fix #2700 : set xaxis/yaxis and chart title color
PHPOffice/PhpSpreadsheet pull request #2701
Opened 2022-03-19 12:24 UTC by rycks

This PR is a partial solution (only excel export) for #2700 : now you can choose font color for xaxis/yaxis/title charts.

2022-04-02 16:37 UTC, MarkBaker commented
Is it possible to provide some unit tests to verify this? Charts is one area that is the least covered by tests, and it really needs some TLC there.

2022-04-02 16:40 UTC, MarkBaker commented
Also, please run a phpcs check to ensure coding complies with the PSR12 standard; phpcbf or php-cs-fixer should be able to fix all these warnings

2022-04-02 16:54 UTC, MarkBaker requested changes
Please address the requested change; and `composer fix` should resolve all the warnings

2022-04-02 16:54 UTC, MarkBaker commented on src/PhpSpreadsheet/Chart/Title.php
> +    public function setFont(Font $font = null)  {
If font defaults to null, the property should also allow null; and the writer should also check for null font when reading the colour

2022-05-15 03:11 UTC, oleibman commented
Converting to draft status for now. There is no need for a `font` property for `Title`, which already has a property `caption`, which can be a `RichText` item, which can already have font information. PR #2828, which I will probably merge this week, uses this information to set chart title color for both export and import.

That PR does not take care of the axis labels (I believe it will handle read correctly but that's only part of the equation). I will look into that soon. Axis labels are more complicated than chart titles because write (export) attempts to reduce the caption from array/string/RichText to a string, and it looks like it does so incorrectly. So it will need further changes, in addition to handling colors.

2022-05-21 16:22 UTC, oleibman commented
Closing - superseded by #2828 and #2841, which are now both merged.

2022-05-21 16:22 UTC, closed without merging