Add support for ignored errors for sheets to now display errors over selected ranges
PHPOffice/PhpSpreadsheet pull request #2723
Opened 2022-04-01 12:00 UTC by jacques

This is:

- [ ] a bugfix
- [x] a new feature

Checklist:

- [ ] Changes are covered by unit tests
- [x] Code style is respected
- [ ] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change
- [ ] Documentation is updated as necessary

### Why this change is needed?

Adds the ability to specify that specific cell ranges should have errors ignored (i.e. when using formulas that reference cells and the formulas next door don't match the one to the left).  This removes the green triangles from being displayed as Excel ignores the error.

2022-04-08 09:11 UTC, jacques commented
@MarkBaker please advise what is required to push this pull request over the line.

2022-04-14 12:40 UTC, MarkBaker commented on src/PhpSpreadsheet/Worksheet/Worksheet.php
> +            $this->ignoredErrors[$errorType][$range] = $range;
What happens if we delete or insert row/columns that are part of the ignore error range?

2022-04-14 12:50 UTC, MarkBaker commented
Can you add some unit tests to show that the details of errors to ignore are being written as expected?

There's some examples on how to approach testing in /tests/PhpSpreadsheetTests/Writer/Xlsx/* where we use the writer calls to return the XML to the test rather than actually saving to a file; and can then assert that the XML contains the markup that's expected.
e.g. ConditionalTest.php and the testWriteSimpleCellConditionalFromWizard() method.

Something like:
```php
namespace PhpOffice\PhpSpreadsheetTests\Writer\Xlsx;

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheetTests\Functional\AbstractFunctional;

class IgnoreErrorsTest extends AbstractFunctional
{
    public function testWriteIgnoreErrors(): void
    {
        $spreadsheet = new Spreadsheet();
        $worksheet = $spreadsheet->getActiveSheet();

        // Code to ignore a set of errors for a range or ranges goes here

        $writer = new Xlsx($spreadsheet);
        $writerWorksheet = new Xlsx\Worksheet($writer);
        $data = $writerWorksheet->writeWorksheet($worksheet, []);

        $expected = <<<XML
//xml for the expected ignoredErrors element markup goes here
XML;
        self::assertStringContainsString($expected, $data);
    }
}
```

2022-04-14 12:50 UTC, MarkBaker requested changes
Please take a look at my comments

2023-06-21 20:25 UTC, oleibman commented
I believe that PR #3508, which was merged in April and should be part of the most recent release, accomplishes what you were requesting.

2023-06-28 14:12 UTC, oleibman commented
Superseded by 3508, closing.

2023-06-28 14:12 UTC, closed without merging

2023-06-28 17:52 UTC, jacques commented
Thank you will check it out.