Allow setting fill colour for bar chart data points
PHPOffice/PhpSpreadsheet pull request #2724
Opened 2022-04-01 13:41 UTC by DanWin

This is:

- [X] a bugfix
- [ ] a new feature

Checklist:

- [ ] Changes are covered by unit tests
- [X] Code style is respected
- [X] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [X] CHANGELOG.md contains a short summary of the change
- [ ] Documentation is updated as necessary

### Why this change is needed?

This will fix #1400 #1433 and #2183

2022-04-02 16:32 UTC, MarkBaker commented
Is it possible to provide some unit tests to verify this for all chart types that are affected?

2022-04-02 16:32 UTC, MarkBaker requested changes

2022-04-02 16:32 UTC, MarkBaker commented on src/PhpSpreadsheet/Writer/Xlsx/Chart.php
> +            if (in_array($groupType, [DataSeries::TYPE_PIECHART, DataSeries::TYPE_PIECHART_3D, DataSeries::TYPE_DONUTCHART, DataSeries::TYPE_BARCHART, DataSeries::TYPE_BARCHART_3D])) {
`in_array()` should always be used in strict mode

2022-04-02 16:49 UTC, MarkBaker requested changes
Please address requested change; and unit testing

2022-04-03 16:06 UTC, DanWin commented
Agreed, `in_array()` should be in strict mode. I saw it mostly being non-strict in other parts of the code and the previous checks were also non-strict and thus kept it the same way.
As for unit testing, I'll need help with that. I've never written those and I'm not sure how to write tests for this case.

2022-04-13 20:19 UTC, MarkBaker commented
> Agreed, `in_array()` should be in strict mode. I saw it mostly being non-strict in other parts of the code and the previous checks were also non-strict and thus kept it the same way.

Thanks. A lot of the code that uses `in_array()` was originally written for earlier versions of PHP, before the strict mode flag was added. Now, we always try to apply it when we're working on those parts of the codebase where it isn't yet applied (scouting rules).

> As for unit testing, I'll need help with that. I've never written those and I'm not sure how to write tests for this case.

There's some examples on how to approach testing in `/tests/PhpSpreadsheetTests/Writer/Xlsx/*` where we use the writer calls to return the XML to the test rather than actually saving to a file; and can then assert that the XML contains the markup that's expected.
e.g. `ConditionalTest.php` and the `testWriteSimpleCellConditionalFromWizard()` method.

Though you might want to create a `Charts` subfolder under `.../Writer/Xlsx/`, and put the test in there.
 
Something like:
```php
namespace PhpOffice\PhpSpreadsheetTests\Writer\Xlsx\Charts;

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheetTests\Functional\AbstractFunctional;

class BarChartTest extends AbstractFunctional
{
    public function testWriteBarChartWithUserDefinedFillColors(): void
    {
        $spreadsheet = new Spreadsheet();
        $worksheet = $spreadsheet->getActiveSheet();

        // Code to create a bar chart with user-defined fill colours goes here

        $writer = new Xlsx($spreadsheet);
        $writerWorksheet = new Xlsx\Worksheet($writer);
        $data = $writerWorksheet->writeWorksheet($worksheet, []);

        $expected = <<<XML
//xml for a bar chart with user-defined fill colours goes here
XML;
        self::assertStringContainsString($expected, $data);
    }
}
```

2022-06-26 06:51 UTC, oleibman commented
This PR will be superseded by #2906, including tests. Converting this to draft; and will close it if 2906 is merged.

2022-06-30 00:53 UTC, oleibman commented
Superseded by 2906, which was just merged.

2022-06-30 00:53 UTC, closed without merging