Fix division by zero warning
PHPOffice/PhpSpreadsheet pull request #3312
Opened 2023-01-21 01:27 UTC by zakariaejaidi

PHP Warning:  Division by zero in /vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Calculation/Financial/CashFlow/Variable/Periodic.php on line 155

This is:

```
- [ x] a bugfix
- [ ] a new feature
- [ ] refactoring
- [ ] additional unit tests
```

Checklist:

- [ ] Changes are covered by unit tests
  - [ ] Changes are covered by existing unit tests
  - [ ] New unit tests have been added
- [x] Code style is respected
- [ ] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change
- [ ] Documentation is updated as necessary

2023-01-21 01:42 UTC, oleibman commented
Do you have a case where this change is needed? If so, please add a unit test to demonstrate its effectiveness?

2023-01-21 11:39 UTC, MarkBaker commented
When we implement a bugfix, we always try to create a unit test to verify the original problem and confirm that the bugfix works as expected. Would you be able to create a unit test for this fix?

2023-02-04 14:55 UTC, MarkBaker requested changes

2023-02-04 14:55 UTC, MarkBaker commented on src/PhpSpreadsheet/Calculation/Financial/CashFlow/Variable/Periodic.php
> +                $returnValue += $val != 0 ? $aArgs[$i - 1] / $val : 0;
`$val` will always be a float, so why do a loose types comparison here?

2024-05-16 04:53 UTC, oleibman commented
No update in over a year. Closing.

2024-05-16 04:53 UTC, closed without merging