Specify data type in html tags using attributes
PHPOffice/PhpSpreadsheet pull request #3445
Opened 2023-03-09 09:58 UTC by PouriaSeyfi

Due to #3444 issue
some times we need specify data type in html using attribute html.
I add new processDomElementDataType function in HTML.php and handle this.

2023-03-09 10:19 UTC, MarkBaker commented on tests/PhpSpreadsheetTests/Reader/Html/HtmlTest.php
> +        self::assertEquals(DataType::TYPE_BOOL, $firstSheet->getCell('A1')->getDataType());
If the data value doesn't match the specified datatype, then you'll need to ensure that it is cast correctly to match the datatype; and make sure that it's set explicitly in the cell to bypass the value binder

2023-03-09 11:25 UTC, PouriaSeyfi commented on tests/PhpSpreadsheetTests/Reader/Html/HtmlTest.php
> +        self::assertEquals(DataType::TYPE_BOOL, $firstSheet->getCell('A1')->getDataType());
Thanks for your guide.
This is considered in the new commit.

2023-03-09 21:25 UTC, PouriaSeyfi commented
There is no any changes. please review my PR.

2023-03-10 09:29 UTC, PouriaSeyfi commented
I had some unwanted changes caused by phpstorm formatter. I fixed them and fixup my commits to new one . 
Also I update my branch with new changes in master. there is no conflict.
Please Review and merge my changes

2023-03-14 11:39 UTC, oleibman commented
I think there is probably some merit in this suggestion. I am trying to think through some of its ramifications. Before I start, there is one minor code change that the PR needs - you do not need to call setDataType after setCellValueExplicit.

Calling setCellValueExplicit can result in an Exception, e.g. if you supply an invalid data type. Is that what we want to happen here, or are we better off catching the Exception and ignoring the format? Regardless of that decision, we need some unit tests for this.

Your example for setting the type to formula is intriguing. However, your test case proves that formulas are already handled without the need to explicitly set the data type. What is not handled is treating a string beginning with an equal sign as a string (by setting quotePrefix to true) rather than a formula. You could accommodate this in your change by checking for this condition if data type is supplied as s.

I think that dates are an especially good use case for this change. You should add some examples for type d (ISO date, time, and date/time elements). Note that those will be converted from string to the Excel numeric representation, and that the conversion may fail.

2023-03-17 00:36 UTC, PouriaSeyfi commented
thanks for your great explanation
I think it is better to check datatypes in flushCell function for better performance. 
As you mentioned it is better to catching the Exception and ignoring the invalid data types.
Also I considered the equal sign in beginning content of cell in case of string datatypes, and I added some new unit test for this scenario and iso dates

2023-03-17 13:32 UTC, oleibman requested changes

2023-03-17 13:32 UTC, oleibman commented on src/PhpSpreadsheet/Reader/Html.php
> +                    if ($datatype == DataType::TYPE_STRING || $datatype == DataType::TYPE_STRING2) {
Do we also need to test for TYPE_INLINE here?

2023-03-17 13:32 UTC, oleibman commented on src/PhpSpreadsheet/Reader/Html.php
> +                        if (substr($cellContent, 0, 1) === '=' || is_numeric($cellContent)) {
I do not understand the purpose of the is_numeric test. Explicitly setting a numeric value to type string should not require quotePrefix. If your testing indicated that it did require it, please add a test to show why.

2023-03-17 13:32 UTC, oleibman commented on tests/PhpSpreadsheetTests/Reader/Html/HtmlTest.php
> +        self::assertEquals($firstSheet->getCell('E1')->getValue(), 44613.43090277778);
We sometimes see rounding problems. Please use assertEqualsWithDelta here; 1E-8 is probably a good enough delta.

2023-03-17 13:32 UTC, oleibman commented on tests/PhpSpreadsheetTests/Reader/Html/HtmlTest.php
> +                        <td data-type="f">=CONCAT("TEXT A ","TEXT B")</td>
I would prefer to eliminate data-type in the formula statement. It should not be necessary. I would still like to retain the formula and the assertions based on it in order to confirm that existing behavior hasn't changed.

2023-03-18 15:37 UTC, merged

2023-03-18 15:37 UTC, oleibman commented
Thank you for your contribution.